apiVersion : apps/v1
kind : Deployment
metadata:
  name: app-demo-kube
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: app-user
        image: icr.io/ibm-demo/ibm-demo:2.0
        ports:
        - containerPort: 5000
